### ISSUE TITLE
Failed while first run Devbox

### ISSUE THREAD

**Issue by vganshin** [Aidbox/Issues#307]
```yaml
version: '3.1'
services:
  aidbox:
    image: "healthsamurai/devbox:0.5.0-SNAPSHOT"
    links:
    - "db:db"
    ports:
    - "8080:8080"
    env_file:
    - .env
    environment:
      AIDBOX_PORT: 8080
      PGHOST: db
      PGDATABASE: mydb
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
    - ./config:/var/config
  db:
    image: "aidbox/db:11.8.6"
    ports:
    - "5435:5432"
    volumes:
    - "./pgdata:/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
```

First time I run `docker-compose up` I face the next error:

```java
20:35:57 :error main [11ms] FATAL: terminating connection due to administrator command SELECT "table_name" FROM "information_schema"."tables" WHERE "table_schema" = ? ["public"]
Exception in thread "main" java.sql.SQLException: An I/O error occurred while sending to the backend.
        at clj_pg.honey$query.invokeStatic(honey.clj:142)
        at clj_pg.honey$query.invoke(honey.clj:139)
        at proto.migration$existing_tables.invokeStatic(migration.clj:184)
        at proto.migration$existing_tables.invoke(migration.clj:183)
        at proto.migration$manifest_from_db.invokeStatic(migration.clj:312)
        at proto.migration$manifest_from_db.invoke(migration.clj:311)
        at proto.box$user_migrate_box.invokeStatic(box.clj:151)
        at proto.box$user_migrate_box.invoke(box.clj:149)
        at proto.box$migrate_box$fn__39958$migrate_fn__39959.invoke(box.clj:240)
        at pg.core$with_connection.invokeStatic(core.clj:94)
        at pg.core$with_connection.invoke(core.clj:91)
        at proto.box$migrate_box$fn__39958$fn__39961.invoke(box.clj:242)
        at proto.box$migrate_box$fn__39958.invoke(box.clj:241)
        at pg.core$with_retry_connection.invokeStatic(core.clj:99)
        at pg.core$with_retry_connection.doInvoke(core.clj:96)
        at clojure.lang.RestFn.invoke(RestFn.java:464)
        at proto.box$migrate_box.invokeStatic(box.clj:227)
        at proto.box$migrate_box.invoke(box.clj:226)
        at proto.box$start.invokeStatic(box.clj:259)
        at proto.box$start.invoke(box.clj:258)
        at box.core$start.invokeStatic(core.clj:22)
        at box.core$start.invoke(core.clj:21)
        at devbox.core$start.invokeStatic(core.clj:118)
        at devbox.core$start.doInvoke(core.clj:104)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at devbox.core$restart.invokeStatic(core.clj:126)
        at devbox.core$restart.invoke(core.clj:124)
        at devbox.core$_main.invokeStatic(core.clj:129)
        at devbox.core$_main.doInvoke(core.clj:128)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:491)
        at clojure.main$main_opt.invoke(main.clj:487)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
```

On second run (when pgdata is exists) `docker-compose up`

**Comment by Zallin** [comment]
I am able to reproduce on compose from https://github.com/Aidbox/devbox
